# Generated by Django 3.2.25 on 2024-09-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('last_communication', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_name', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
                ('epc', models.CharField(max_length=255)),
                ('first_seen_timestamp', models.DateTimeField()),
                ('antenna_port', models.IntegerField()),
                ('antenna_zone', models.CharField(max_length=255)),
                ('peak_rssi', models.FloatField()),
                ('tx_power', models.FloatField()),
                ('tag_data_key', models.CharField(max_length=255)),
                ('tag_data_key_name', models.CharField(max_length=255)),
                ('tag_data_serial', models.CharField(max_length=255)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('status-detailed', 'Status Detailed'), ('mode', 'Mode')], max_length=50)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reader')),
            ],
        ),
    ]
