# Generated by Django 3.2.25 on 2024-09-25 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('mac_address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('details', models.JSONField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reader')),
            ],
        ),
    ]
