# Generated by Django 3.2.25 on 2024-09-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_detailedstatusevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedstatusevent',
            name='non_antenna_details',
            field=models.JSONField(default=dict),
        ),
    ]
