# Generated by Django 3.2.25 on 2024-09-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_detailedstatusevent_non_antenna_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedstatusevent',
            name='non_antenna_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
