# Generated by Django 3.2.25 on 2024-09-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_detailedstatusevent_non_antenna_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'verbose_name': 'Command', 'verbose_name_plural': 'Commands'},
        ),
        migrations.AddField(
            model_name='command',
            name='command',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Command'),
        ),
        migrations.AddField(
            model_name='command',
            name='response',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Response'),
        ),
        migrations.AddField(
            model_name='command',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_type',
            field=models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('status-detailed', 'Status Detailed'), ('mode', 'Mode')], max_length=50, verbose_name='Command Type'),
        ),
        migrations.AlterField(
            model_name='command',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Sent'),
        ),
        migrations.AlterField(
            model_name='command',
            name='details',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='command',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reader', verbose_name='Reader'),
        ),
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
    ]
