# Generated by Django 3.2.25 on 2024-09-30 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20240927_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('condition_type', models.CharField(choices=[('tag_frequency', 'Tag Read Frequency'), ('reader_status', 'Reader Status Change'), ('tag_pattern', 'Specific Tag Pattern'), ('access_violation', 'Access Control Violation')], max_length=20, verbose_name='Condition Type')),
                ('condition_params', models.JSONField(verbose_name='Condition Parameters')),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('in_app', 'In-App Notification')], max_length=10, verbose_name='Notification Method')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Triggered At')),
                ('details', models.JSONField(verbose_name='Details')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alert', verbose_name='Alert')),
            ],
        ),
    ]
