# Generated by Django 3.2.25 on 2024-09-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240930_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop'), ('status-detailed', 'Status Detailed'), ('mode', 'Mode')], max_length=50, verbose_name='Command Type')),
                ('scheduled_time', models.DateTimeField(verbose_name='Scheduled Time')),
                ('recurrence', models.CharField(choices=[('ONCE', 'Once'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='ONCE', max_length=10, verbose_name='Recurrence')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reader', verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'Scheduled Command',
                'verbose_name_plural': 'Scheduled Commands',
            },
        ),
    ]
