# Generated by Django 3.2.20 on 2024-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_taskexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Command ID'),
        ),
    ]
