# Generated by Django 3.2.20 on 2024-10-02 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_command_command_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('file', models.FileField(upload_to='firmware/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['upgx'])])),
                ('description', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FirmwareUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.firmware')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reader')),
            ],
        ),
    ]
