# Generated by Django 3.2.20 on 2024-10-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_firmware_firmwareupdatestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware',
            name='checksum',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
