version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/app/
    depends_on:
      - mqtt
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=smartreaderdb
      - POSTGRES_USER=smartreader_user
      - POSTGRES_PASSWORD=smartreader_password
    ports:
      - "5432:5432"
    networks:
      - app_network

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
