version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/app/
    depends_on:
      - mqtt
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://smartreader_user:smartreader_password@db:5432/smartreaderdb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  
    networks:
      - app_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=smartreaderdb
      - POSTGRES_USER=smartreader_user
      - POSTGRES_PASSWORD=smartreader_password
    ports:
      - "5432:5432"
    networks:
      - app_network

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - app_network
  
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - ./src:/app
    depends_on:
      - mqtt
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://smartreader_user:smartreader_password@db:5432/smartreaderdb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
