version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/app/
    depends_on:
      - mqtt
      - db
      - redis
    environment:
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_BROKER=${MQTT_BROKER}
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DB_SSL_REQUIRE=${DB_SSL_REQUIRE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}  
    networks:
      - app_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=smartreaderdb
      - POSTGRES_USER=smartreader_user
      - POSTGRES_PASSWORD=smartreader_password
    ports:
      - "5432:5432"
    networks:
      - app_network

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    networks:
      - app_network
  
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app_network

  celery:
    build: .
    command: celery -A config worker -l info
    volumes:
      - ./src:/app
    depends_on:
      - mqtt
      - db
      - redis
    environment:
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_BROKER=${MQTT_BROKER}
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DB_SSL_REQUIRE=${DB_SSL_REQUIRE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}  
    networks:
      - app_network
  
  celery-beat:
    build: .
    command: celery -A config beat -l info
    volumes:
      - ./src:/app
    depends_on:
      - celery
    environment:
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_BROKER=${MQTT_BROKER}
      - SECURE_SSL_REDIRECT=${SECURE_SSL_REDIRECT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DB_SSL_REQUIRE=${DB_SSL_REQUIRE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}  
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
