apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mqtt-pub
spec:
  type: pubsub.mqtt
  version: v1
  metadata:
    - name: url
      value: "mqtt://mqtt:1883"  # Replace with your MQTT broker URL
    - name: qos
      value: "1"
    - name: retain
      value: "false"