"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import ssl
import sys
import dj_database_url 
from celery.schedules import crontab
from datetime import timedelta
from datetime import datetime
from pathlib import Path
from kombu import Exchange, Queue

TESTING = len(sys.argv) > 1 and sys.argv[1] == 'test'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-(f$i52gweksrqad2=)n5qo@we-&226!(&kmlcj)2w7$kyq^riy')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ALLOWED_HOSTS = ['web','localhost','127.0.0.1']

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Redirect all HTTP traffic to HTTPS
# UNCOMMENT FOR PRODUCTION DEPLOYMENT
# SECURE_SSL_REDIRECT = True
# SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', True)

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    SECURE_PROXY_SSL_HEADER = None

if not DEBUG:
    SECURE_SSL_REDIRECT = True
else:
    SECURE_SSL_REDIRECT = False


# Optionally: HSTS settings
# SECURE_HSTS_SECONDS = 31536000  # Enable HTTP Strict Transport Security (HSTS)
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django_celery_beat',
    #'django_celery_results',
    'rest_framework',
    'app',
    'mqtt_service',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.APIKeyMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

print(f"DATABASE_URL: {os.environ.get('DATABASE_URL')}")

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=os.environ.get('DB_SSL_REQUIRE', 'False') == 'True'
    )
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    },
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'app.authentication.APIKeyAuthentication',
    ],

}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
# TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    # Add other languages as needed
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

FIRMWARE_URL_BASE = 'http://192.168.68.118:8000/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MQTT Broker Configuration
MQTT_PORT = os.environ.get('MQTT_PORT', 1883)
MQTT_BROKER = os.environ.get('MQTT_BROKER', 'test.mosquitto.org')
MQTT_MAX_MESSAGE_SIZE = os.environ.get('MQTT_MAX_MESSAGE_SIZE', 268435455)
MQTT_MAX_RECONNECT_ATTEMPTS = os.environ.get('MQTT_MAX_RECONNECT_ATTEMPTS', 5)
MQTT_RECONNECT_DELAY = os.environ.get('MQTT_RECONNECT_DELAY', 5)
MQTT_MAX_RECONNECT_ATTEMPTS = os.environ.get('MQTT_MAX_RECONNECT_ATTEMPTS', 5)
MQTT_KEEPALIVE = os.environ.get('MQTT_KEEPALIVE', 60)
MQTT_QOS = os.environ.get('MQTT_QOS', 1)
MQTT_RETAIN = os.environ.get('MQTT_RETAIN', False)
MQTT_USE_TLS = os.environ.get('MQTT_USE_TLS', False)
MQTT_CA_CERTS  = os.environ.get('MQTT_CA_CERTS', '/path/to/ca.crt')
MQTT_CERTFILE   = os.environ.get('MQTT_CERTFILE ', None)
MQTT_KEYFILE   = os.environ.get('MQTT_KEYFILE ', None)
MQTT_VERIFY_HOSTNAME   = os.environ.get('MQTT_VERIFY_HOSTNAME ', None)
MQTT_TLS_VERSION   = os.environ.get('MQTT_TLS_VERSION ', ssl.PROTOCOL_TLS_CLIENT)
MQTT_CIPHERS   = os.environ.get('MQTT_CIPHERS ', None)

MQTT_TOPICS = [
    ('smartreader/+/controlResult', 1),
    ('smartreader/+/manageResult', 1),
    ('smartreader/+/tagEvents', 1),
    ('smartreader/+/event', 1),
    ('smartreader/+/metrics', 1),
    ('smartreader/+/lwt', 1),

    ]

# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'amqp://user:password@rabbitmq:5672//')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'django-db')
CELERY_TASK_QUEUES = (
    Queue('default', Exchange('default'), routing_key='default'),
    Queue('scheduled_commands', Exchange('scheduled_commands'), routing_key='scheduled_commands'),
    Queue('high_priority', Exchange('high_priority'), routing_key='high_priority'),
    Queue('low_priority', Exchange('low_priority'), routing_key='low_priority'),
)


CELERY_TASK_ROUTES = {
    'app.tasks.process_and_cleanup_commands': {'queue': 'high_priority'},
    'app.tasks.execute_scheduled_commands_task': {'queue': 'scheduled_commands'},
    'app.tasks.process_pending_commands': {'queue': 'high_priority'},
}

CELERY_BEAT_SCHEDULE = {}

CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_DEFAULT_EXCHANGE = "default"
CELERY_TASK_DEFAULT_ROUTING_KEY = "default"

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'reader_list'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        # 'file': {
        #     'level': 'DEBUG',
        #     'class': 'logging.FileHandler',
        #     'filename': 'logs/debug.log',
        #     'formatter': 'verbose',
        # },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'app.api_views': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'celery': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'app': {  # Your Django app name
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}



# Ensure the logs directory exists
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)
